component_depth: 1
languages:
- java
- script
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/roller/.*
- ./bin/org/apache/roller/planet/.*
- ./bin/org/apache/roller/planet/business/.*
- ./bin/org/apache/roller/planet/business/fetcher/.*
- ./bin/org/apache/roller/planet/business/jpa/.*
- ./bin/org/apache/roller/planet/business/startup/.*
- ./bin/org/apache/roller/planet/business/updater/.*
- ./bin/org/apache/roller/planet/config/.*
- ./bin/org/apache/roller/planet/config/runtime/.*
- ./bin/org/apache/roller/planet/pojos/.*
- ./bin/org/apache/roller/planet/tasks/.*
- ./bin/org/apache/roller/planet/ui/.*
- ./bin/org/apache/roller/planet/ui/admin/.*
- ./bin/org/apache/roller/planet/ui/admin/struts2/.*
- ./bin/org/apache/roller/planet/ui/core/.*
- ./bin/org/apache/roller/planet/ui/core/filters/.*
- ./bin/org/apache/roller/planet/ui/core/struts2/.*
- ./bin/org/apache/roller/planet/ui/rendering/.*
- ./bin/org/apache/roller/planet/ui/rendering/filters/.*
- ./bin/org/apache/roller/planet/ui/rendering/model/.*
- ./bin/org/apache/roller/planet/ui/rendering/pagers/.*
- ./bin/org/apache/roller/planet/ui/rendering/servlets/.*
- ./bin/org/apache/roller/planet/ui/rendering/util/.*
- ./bin/org/apache/roller/planet/ui/rendering/velocity/.*
- ./bin/org/apache/roller/planet/util/.*
- ./bin/org/apache/roller/planet/util/rome/.*
- ./bin/org/apache/roller/util/.*
- ./bin/org/apache/roller/weblogger/.*
- ./bin/org/apache/roller/weblogger/ant/.*
- ./bin/org/apache/roller/weblogger/jetty/.*
- ./lib/.*
- ./planet-business/.*
- ./planet-web/.*
- ./roller-core/.*
- ./test-utils/.*
- ./weblogger-assembly/.*
- ./weblogger-business/.*
- ./weblogger-docs/.*
- ./weblogger-docs/devguide/.*
- ./weblogger-docs/examples/.*
- ./weblogger-docs/examples/configs/.*
- ./weblogger-docs/examples/configs/resin/.*
- ./weblogger-docs/examples/configs/tomcat/.*
- ./weblogger-docs/examples/configs/wbloggar/.*
- ./weblogger-docs/examples/macros/.*
- ./weblogger-docs/examples/plugins/.*
- ./weblogger-docs/examples/plugins/pluginmodel/.*
- ./weblogger-docs/examples/rollertask/.*
- ./weblogger-docs/examples/scripting/.*
- ./weblogger-docs/examples/scripting/bsf/.*
- ./weblogger-docs/examples/scripting/bsf/lib/.*
- ./weblogger-docs/examples/scripting/groovy/.*
- ./weblogger-docs/examples/scripting/groovy/examples/.*
- ./weblogger-docs/examples/scripting/groovy/examples/adminprotocol/.*
- ./weblogger-docs/examples/scripting/groovy/examples/adminprotocol/lib/.*
- ./weblogger-docs/examples/scripting/groovy/examples/atompub/.*
- ./weblogger-docs/examples/scripting/groovy/examples/rollerapi/.*
- ./weblogger-docs/examples/scripting/groovy/examples/rollerapi/logs/.*
- ./weblogger-docs/installguide/.*
- ./weblogger-docs/installguide/generated/.*
- ./weblogger-docs/installguide/generated/html/.*
- ./weblogger-docs/installguide/old/.*
- ./weblogger-docs/templateguide/.*
- ./weblogger-docs/templateguide/generated/.*
- ./weblogger-docs/templateguide/generated/html/.*
- ./weblogger-docs/testing/.*
- ./weblogger-docs/userguide/.*
- ./weblogger-docs/userguide/generated/.*
- ./weblogger-docs/userguide/generated/html/.*
- ./weblogger-war-assembly/.*
- ./weblogger-web/.*
- ./weblogger-webapp/.*
